### ISSUE TITLE
button nya koq ga bisa di pencet bang?

### ISSUE THREAD

**Issue by Arya-was** [Nino-chan02/SelfBotz#2]
https://github.com/Nino-chan02/SelfBotz/blob/main/nino.js#L642
di pencet next ga terjadi apa apa

**Comment by Nino-chan02** [comment]
![IMG_20210809_185447](https://user-images.githubusercontent.com/81684610/128702281-82c2008d-3b71-4872-963f-1561f3b5bf62.jpg)
